export {default as Header} from './Header'
export {default as Authorization} from './Authorization'
export {default as Authorization2} from './Authorization'
export {default as Registration} from './Registration'
export {default as Input} from './Input'
export {default as Profile} from './Profile'
export {default as Home} from './Home'